name: API Service
run-name: Workflow run on ${{ github.ref_name }}
on:
  delete:
    tags:
      - '*'

jobs:
  delete-tags:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
      
      - name: Delete DockerHub Tag
        run: |
          #!/bin/bash
          USERNAME=${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
          TAG=${{ github.ref }}
        
          echo "${USERNAME}"
          echo "${PASSWORD}"