name: API Service
run-name: Workflow run on ${{ github.ref }}
on:
  delete:
    tags:
      - '*'

jobs:
  delete-tags:
      runs-on: ubuntu-latest
      if: github.event_name == 'delete'
      steps:
        - name: Login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install jq
          run: |
            sudo apt-get update
            sudo apt-get install jq
      
        - name: Delete DockerHub Tag
          run: |
            UNAME="${{ vars.DOCKERHUB_USERNAME }}"
            UPASS="${{ secrets.DOCKERHUB_PASSWORD }}"
            REPO_NAME="${{ vars.DOCKERHUB_USERNAME }}"
            IMAGE_NAME="obsrv-api-service"
            TAG_NAME="release-1.4-alpha"
            
            TOKEN=$(curl -sS -H "Content-Type: application/json" -X POST -d '{"username": "'${UNAME}'", "password": "'${UPASS}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          
            # Get the image digest
            # DIGEST=$(curl -sS -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://hub.docker.com/v2/repositories/${REPO_NAME}/${IMAGE_NAME}/manifests/${TAG_NAME} | jq .config.digest)
            DIGEST=$(curl -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -k -v -X GET https://hub.docker.com/v2/repositories/surabhi1510/obsrv-api-service/manifests/release-1.4-alpha)
          
            # # Delete the image
            # curl -sS -X DELETE -H "Authorization: Bearer ${TOKEN}" https://hub.docker.com/v2/repositories/${REPO_NAME}/${IMAGE_NAME}/manifests/${DIGEST}
