name: API Service
run-name: Workflow run on ${{ github.ref_name }}
on:
  delete:
    tags:
      - '*'

jobs:
  delete-tags:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
      
      - name: Delete DockerHub Tag
        run: |
          #!/bin/bash
          USERNAME=${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
          TAG=${{ vars.DOCKERHUB_USERNAME }}/obsrv-api-service:${{ github.ref_name }}
          
          #Authenticate
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -H "Content-Type: application/json" \
                      -d '{"username": "'"$USERNAME"'","password": "'"$PASSWORD"'"}'\
                      "https://hub.docker.com/v2/users/login/" | jq -r '.token')
          echo  "Token: ${TOKEN}"

          #Delete tag
          response=$(curl "https://hub.docker.com/v2/repositories/$USERNAME/$IMAGE_NAME/tags/$TAG/" -X DELETE -H "Authorization: JWT ${TOKEN}")
