name: API Service
run-name: Workflow run on ${{ github.ref_name }}
on: delete


jobs:
  delete-tags:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
      
      - name: Delete DockerHub Tag
        run: |
          #!/bin/bash
          USERNAME=${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
          IMAGE_NAME=obsrv-api-service
          TAG=test-delete-tag-action-17
          # TAG=${{ github.ref_name }}
          
          #Authenticate
          TOKEN=$(curl -vvv -s -H "Content-Type: application/json" -X POST -H "Content-Type: application/json" \
                      -d '{"username": "'"$USERNAME"'","password": "'"$PASSWORD"'"}'\
                      "https://hub.docker.com/v2/users/login/" | jq -r '.token')
          echo  "Token: ${TOKEN}"

          #Delete tag
          response=$(curl -vvv "https://hub.docker.com/v2/repositories/$USERNAME/$IMAGE_NAME/tags/$TAG/" -X DELETE -H "Authorization: JWT ${TOKEN}")
          echo "Response: ${response}"

          if echo "$response" | grep -q 'HTTP/1.1 204 '; then
            echo "Tag deleted"
          else
            error_message=$(echo "$response" | awk '/< HTTP/ { print "HTTP status: " $3 }; /{"errors":/ { print }')
            echo "Tag deletion failed: $error_message"
          fi
