name: API Service
run-name: Workflow run on ${{ github.ref }}
on:
  delete:

jobs:
  delete-tags:
      runs-on: ubuntu-latest
      steps:
        - name: Delete tag from Docker  
          run: |
            #!/bin/bash
            # Script to delete a Docker Hub image tags    
            DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
            docker run --rm -it lumir/remove-dockerhub-tag --user ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD} ${{ vars.DOCKERHUB_USERNAME }}/obsrv-api-service:${{ github.ref_name }}
            
            